version: '3.7'
services:
  app:
    volumes:
      - vscode-server:/root/.vscode-server
    command: >
      bash -c
      "npm install
      && sleep infinity"
volumes:
  vscode-server:
    driver: local
