FROM ruby:2.6.2@sha256:d5af6b19da8381014f59e79245ae242dd5ea8dfe1a8a6c0e2bc481366f1e92b9

RUN apt update \
  && apt install --assume-yes --no-install-recommends build-essential libmysql-cil-dev mysql-client
